# This is a basic workflow to help you get started with Actions

name: e2e-tests

# Controls when the workflow will run
on:
  pull_request_target:
    types: [ labeled ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BASE_SHA: ${{ github.event.pull_request.base.sha }}
  HEAD_SHA: ${{ github.event.pull_request.head.sha }}
  PR_ID: ${{ github.event.pull_request.number }}
  TF_ACC: true
  TENCENTCLOUD_REGION: ap-guangzhou
  TENCENTCLOUD_SECRET_KEY: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
  TENCENTCLOUD_SECRET_ID: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
  TENCENTCLOUD_APPID: ${{ secrets.TENCENTCLOUD_APPID }}
  TENCENTCLOUD_OWNER_UIN: ${{ secrets.TENCENTCLOUD_OWNER_UIN }}
  TENCENTCLOUD_SECRET_ID_INTERNATIONAL: ${{ secrets.TENCENTCLOUD_SECRET_ID_INTERNATIONAL }}
  TENCENTCLOUD_SECRET_KEY_INTERNATIONAL: ${{ secrets.TENCENTCLOUD_SECRET_KEY_INTERNATIONAL }}
  TENCENTCLOUD_SECRET_ID_PREPAY: ${{ secrets.TENCENTCLOUD_SECRET_ID_PREPAY }}
  TENCENTCLOUD_SECRET_KEY_PREPAY: ${{ secrets.TENCENTCLOUD_SECRET_KEY_PREPAY }}
  TENCENTCLOUD_SECRET_ID_PRIVATE: ${{ secrets.TENCENTCLOUD_SECRET_ID_PRIVATE }}
  TENCENTCLOUD_SECRET_KEY_PRIVATE: ${{ secrets.TENCENTCLOUD_SECRET_KEY_PRIVATE }}
  TENCENTCLOUD_SECRET_KEY_COMMON: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
  TENCENTCLOUD_SECRET_ID_COMMON: ${{ secrets.TENCENTCLOUD_SECRET_ID }}
  TENCENTCLOUD_SECRET_KEY_SUB_ACCOUNT: ${{ secrets.TENCENTCLOUD_SECRET_KEY_SUB_ACCOUNT }}
  TENCENTCLOUD_SECRET_ID_SUB_ACCOUNT: ${{ secrets.TENCENTCLOUD_SECRET_ID_SUB_ACCOUNT }}
  TENCENTCLOUD_SECRET_KEY_SMS: ${{ secrets.TENCENTCLOUD_SECRET_KEY_SMS }}
  TENCENTCLOUD_SECRET_ID_SMS: ${{ secrets.TENCENTCLOUD_SECRET_ID_SMS }}
  TENCENTCLOUD_SECRET_KEY_TSF: ${{ secrets.TENCENTCLOUD_SECRET_KEY_TSF }}
  TENCENTCLOUD_SECRET_ID_TSF: ${{ secrets.TENCENTCLOUD_SECRET_ID_TSF }}
  TENCENTCLOUD_SECRET_KEY_SSL: ${{ secrets.TENCENTCLOUD_SECRET_KEY_SSL }}
  TENCENTCLOUD_SECRET_ID_SSL: ${{ secrets.TENCENTCLOUD_SECRET_ID_SSL }}
  TENCENTCLOUD_SECRET_ID_ORGANIZATION: ${{ secrets.TENCENTCLOUD_SECRET_ID_ORGANIZATION }}
  TENCENTCLOUD_SECRET_KEY_ORGANIZATION: ${{ secrets.TENCENTCLOUD_SECRET_KEY_ORGANIZATION }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  e2e-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      # Runs a set of commands using the runners shell
      - name: e2e tests
        run: |
          make dispachertest
          if [ $? -ne 0 ]; then
              printf "COMMIT FAILED\n"
              exit 1
          fi
