# This is a basic workflow to help you get started with Actions

name: gofmt

# Controls when the workflow will run
on:
  pull_request:
#    paths:
#      - tencentcloud/**
     paths-ignore:
       - *

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  fmt:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.18

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      # Runs a set of commands using the runners shell
      - name: gofmt check
        run: |
          make fmtcheck
          if [ $? -ne 0 ]; then
              printf "FMT FAILED\n"
              exit 1
          fi

