# This is a basic workflow to help you get started with Actions

name: MR_CHECK

# Controls when the workflow will run
on:
  pull_request_target:
    types: [labeled]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
            ref: ${{ github.event.pull_request.head.sha }}

      # Runs a set of commands using the runners shell
      - name: MR INFO
        run: |
          git fetch origin master
          
          export TF_ACC=true
          export TENCENTCLOUD_REGION=ap-guangzhou
          export TENCENTCLOUD_SECRET_KEY=${{ secrets.TENCENTCLOUD_SECRET_KEY }}
          export TENCENTCLOUD_SECRET_ID=${{ secrets.TENCENTCLOUD_SECRET_ID }}
          export TENCENTCLOUD_APPID=${{ secrets.TENCENTCLOUD_APPID }}
          export TENCENTCLOUD_OWNER_UIN=${{ secrets.TENCENTCLOUD_OWNER_UIN }}
          export TENCENTCLOUD_SECRET_ID_INTERNATION=${{ secrets.TENCENTCLOUD_SECRET_ID_INTERNATION }}
          export TENCENTCLOUD_SECRET_KEY_INTERNATION=${{ secrets.TENCENTCLOUD_SECRET_KEY_INTERNATION }}
          export TENCENTCLOUD_SECRET_ID_PREPAY=${{ secrets.TENCENTCLOUD_SECRET_ID_PREPAY }}
          export TENCENTCLOUD_SECRET_KEY_PREPAY=${{ secrets.TENCENTCLOUD_SECRET_KEY_PREPAY }}
          export TENCENTCLOUD_SECRET_ID_PRIVATE=${{ secrets.TENCENTCLOUD_SECRET_ID_PRIVATE }}
          export TENCENTCLOUD_SECRET_KEY_PRIVATE=${{ secrets.TENCENTCLOUD_SECRET_KEY_PRIVATE }}
          export TENCENTCLOUD_SECRET_KEY_COMMON=${{ secrets.TENCENTCLOUD_SECRET_KEY }}
          export TENCENTCLOUD_SECRET_ID_COMMON=${{ secrets.TENCENTCLOUD_SECRET_ID }}
          export TENCENTCLOUD_SECRET_KEY_SUB_ACCOUNT=${{ secrets.TENCENTCLOUD_SECRET_KEY_SUB_ACCOUNT }}
          export TENCENTCLOUD_SECRET_ID_SUB_ACCOUNT=${{ secrets.TENCENTCLOUD_SECRET_ID_SUB_ACCOUNT }}
          sh .githooks/pre-commit
